title: N Nelson
logo: /assets/img/logo.png
description:  I am currently working on Data Science, Big Data, Machine learning & Artificial Intelligence related problems.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
