title: N Nelson
logo: /assets/img/logopic.png
description:  Technology Head | North West India Baptist Association
Owner | NJ Enterprises
Director | Oasys Online Experts Pvt Ltd
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
